const {_electron:electron}=require('playwright');const fs=require('node:fs'),path=require('node:path'),os=require('node:os');const assert=require('node:assert/strict');
(async()=>{
 const home=fs.mkdtempSync(path.join(os.tmpdir(),'machen-language-')),dir=path.join(home,'data');fs.mkdirSync(dir);
 fs.writeFileSync(path.join(home,'settings.json'),JSON.stringify({directory:dir,language:'de',theme:'dark',shortcut:'Alt+Shift+F8'}));
 fs.writeFileSync(path.join(dir,'todo.txt'),'2026-09-09 Heute +Archiv @Telefon id:keep\n');
 const launch=()=>electron.launch({...(process.env.MACHEN_EXECUTABLE?{executablePath:process.env.MACHEN_EXECUTABLE,args:[]}:{args:['.']}),env:{...process.env,MACHEN_TEST_HOME:home}});
 let app;const mainPage=async()=>{await app.firstWindow();for(let i=0;i<100;i++){const page=app.windows().find(p=>p.url().includes('index.html')&&!p.url().includes('quick=1'));if(page)return page;await new Promise(resolve=>setTimeout(resolve,50));}throw Error('Main window did not load');};try{
  app=await launch();const page=await mainPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.locator('.task-title').filter({hasText:'Heute'}).click();
  await page.locator('#notes').fill('Nicht übersetzen');
  await page.locator('.sidebar [data-language]').selectOption('en');
  await page.getByRole('heading',{name:'Today',exact:true}).waitFor();
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  assert.equal(await page.locator('#notes').inputValue(),'Nicht übersetzen');
  assert.equal(await page.locator('#detail-title').inputValue(),'Heute');
  assert.equal(await page.locator('.sidebar [data-project="Archiv"] .project-chip').textContent(),'Archiv');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await page.getByRole('heading',{name:'Delete task?',exact:true}).waitFor();await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('button',{name:'Close details'}).click();
  await page.getByRole('textbox',{name:'New task',exact:true}).fill('Invalid id:reserved');
  await page.getByRole('button',{name:'Add',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Please enter a title without reserved'}).waitFor();
  await page.getByRole('button',{name:'Expand task details'}).click();
  await page.getByRole('textbox',{name:'New task',exact:true}).fill('Keep this draft');
  await page.locator('select[aria-label="Filter by due date"]').selectOption('today');
  assert.ok(await page.getByText('No tasks match these filters.',{exact:true}).count());
  await page.getByRole('button',{name:'Reset',exact:true}).click();
  await page.evaluate(()=>window.api.call('quick'));const quick=app.windows().find(w=>w!==page);
  await quick.getByRole('textbox',{name:'New task',exact:true}).fill('Quick draft');
  await quick.getByRole('button',{name:'Expand task details'}).click();
  await quick.getByText('Due date',{exact:true}).waitFor();
  await page.locator('.sidebar [data-language]').selectOption('de');
  await quick.getByText('Fällig am',{exact:true}).waitFor();
  assert.equal(await quick.getByRole('textbox',{name:'Neue Aufgabe',exact:true}).inputValue(),'Quick draft');
  assert.equal(await page.getByRole('textbox',{name:'Neue Aufgabe',exact:true}).inputValue(),'Keep this draft');
  await page.locator('.sidebar [data-language]').selectOption('en');
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.getByRole('heading',{name:'Settings',exact:true}).waitFor();
  await page.getByRole('heading',{name:'Quick capture',exact:true}).waitFor();
  const menu=await app.evaluate(({Menu})=>Menu.getApplicationMenu().items.map(x=>x.label));assert.deepEqual(menu,['Machen','Edit','View']);
  fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/english-settings.png'});
  assert.equal(errors.length,0,errors.join('\n'));await app.close();app=await launch();
  const restored=await mainPage();await restored.getByRole('heading',{name:'Today',exact:true}).waitFor();
  assert.equal((await restored.evaluate(()=>window.api.call('state'))).settings.language,'en');
  assert.match(fs.readFileSync(path.join(dir,'todo.txt'),'utf8'),/Heute \+Archiv @Telefon/);
  await app.close();const config=JSON.parse(fs.readFileSync(path.join(home,'settings.json'),'utf8'));config.directory='';fs.writeFileSync(path.join(home,'settings.json'),JSON.stringify(config));app=await launch();
  await (await mainPage()).getByRole('button',{name:'Choose storage folder',exact:true}).waitFor();
  console.log('PASS German/English UI, dialogs, filters, native menus, popup sync, drafts, unchanged user content, persistence and onboarding');
 }finally{if(app)await app.close();fs.rmSync(home,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
