const {_electron:electron}=require('playwright');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');

(async()=>{
  const home=fs.mkdtempSync(path.join(os.tmpdir(),'machen-qol-')),dir=path.join(home,'data');fs.mkdirSync(dir);
  fs.writeFileSync(path.join(home,'settings.json'),JSON.stringify({directory:dir,language:'en',theme:'dark',shortcut:'Alt+Shift+F4'}));
  fs.writeFileSync(path.join(dir,'todo.txt'),'2026-09-09 Work task +Work @Office id:one\n2026-09-09 Personal task +Home @Phone id:two\nx 2026-09-09 2026-09-08 Finished +Closed @Done id:three\n');
  let app;
  try{
    app=await electron.launch({args:['.'],env:{...process.env,MACHEN_TEST_HOME:home}});
    const page=await app.firstWindow();
    assert.equal(await page.locator('[data-project="Closed"]').count(),0);
    assert.equal(await page.locator('[data-context="Done"]').count(),0);
    await page.locator('[data-project="Work"]').click();
    await page.getByRole('heading',{name:'Work',exact:true}).waitFor();
    await page.getByRole('textbox',{name:'New task',exact:true}).fill('Project note');
    await page.getByRole('button',{name:'Add',exact:true}).click();
    const created=(await page.evaluate(()=>window.api.call('state'))).tasks.find(task=>task.title.startsWith('Project note'));
    assert.match(created.title,/\+Work/);
    await page.locator('[data-context="Office"]').click();
    await page.getByRole('heading',{name:'@Office',exact:true}).waitFor();
    assert.equal(await page.locator('.task-title').count(),1);
    await page.getByRole('textbox',{name:'New task',exact:true}).fill('Context note');
    await page.getByRole('button',{name:'Add',exact:true}).click();
    const contextTask=(await page.evaluate(()=>window.api.call('state'))).tasks.find(task=>task.title.startsWith('Context note'));
    assert.match(contextTask.title,/@Office/);
    await page.getByText('Context note',{exact:true}).click({button:'right'});
    await page.getByRole('menu',{name:'Task actions'}).waitFor();
    await page.getByRole('menuitem',{name:'Schedule for tomorrow'}).click();
    const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const planned=tomorrow.toISOString().slice(0,10);
    await page.waitForFunction(day=>window.api.call('state').then(s=>s.tasks.some(task=>task.title.startsWith('Context note')&&task.scheduled===day)),planned);
    await page.locator('[data-project="Work"]').click({button:'right'});
    await page.getByRole('menu',{name:'Actions for +Work'}).getByRole('menuitem',{name:'New task in +Work'}).click();
    await page.getByRole('heading',{name:'Work',exact:true}).waitFor();
    await page.getByRole('textbox',{name:'New task',exact:true}).waitFor();
    const list=await page.locator('.sidebar-lists').evaluate(item=>({overflow:getComputedStyle(item).overflowY,flex:getComputedStyle(item).flexGrow}));
    assert.deepEqual(list,{overflow:'auto',flex:'1'});
    await page.getByRole('button',{name:'Settings',exact:true}).click();
    assert.equal(await page.locator('[role=tab]').count(),4);
    assert.equal(await page.getByRole('button',{name:'Save settings',exact:true}).count(),0);
    await page.keyboard.press('Control+K');
    await page.getByRole('dialog').waitFor();
    await page.getByRole('searchbox',{name:'Command palette'}).fill('Work task');
    await page.getByRole('option',{name:/Work task/}).click();
    await page.getByRole('heading',{name:'All tasks',exact:true}).waitFor();
    await page.locator('.command-palette').waitFor({state:'detached'});
    await page.locator('.workspace .task-title',{hasText:'Work task'}).waitFor();
    await page.getByRole('button',{name:'Close details',exact:true}).click();
    await page.getByRole('button',{name:'Settings',exact:true}).click();
    await page.locator('[data-settings-tab="reminders"]').click();
    assert.equal(await page.getByRole('checkbox',{name:'Enable due date reminders'}).isChecked(),false);
    await page.evaluate(()=>window.api.call('reminderSettings',{enabled:true,time:'23:59',leadMinutes:60}));
    await page.waitForFunction(()=>window.api.call('state').then(s=>s.settings.remindersEnabled&&s.settings.reminderTime==='23:59'&&s.settings.reminderLeadMinutes===60));
    await page.locator('select[name=reminderHour]').waitFor({state:'attached'});
    assert.equal(await page.locator('select[name=reminderMinute]').inputValue(),'59');
    await page.getByRole('combobox',{name:'Hours'}).click();
    await page.getByRole('option',{name:'07',exact:true}).click();
    await page.getByRole('combobox',{name:'Minutes'}).click();
    await page.getByRole('option',{name:'30',exact:true}).click();
    await page.waitForFunction(()=>window.api.call('state').then(s=>s.settings.reminderTime==='07:30'));
    await page.getByRole('combobox',{name:'Reminder before due time'}).click();
    await page.getByRole('option',{name:'30 minutes before',exact:true}).click();
    await page.waitForFunction(()=>window.api.call('state').then(s=>s.settings.reminderLeadMinutes===30));
    fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/reminder-settings.png'});
    await page.locator('[data-settings-tab="app"]').click();
    await page.getByRole('button',{name:'Change shortcut',exact:true}).click();
    await page.getByText('Press the shortcut you want to use.',{exact:true}).waitFor();
    await page.keyboard.press('Control+Alt+K');
    assert.equal(await page.locator('#shortcut').inputValue(),'CommandOrControl+Alt+K');
    await page.waitForFunction(()=>window.api.call('state').then(s=>s.settings.shortcut==='CommandOrControl+Alt+K'));
    assert.equal(await app.evaluate(({globalShortcut})=>globalShortcut.isRegistered('CommandOrControl+Alt+K')),true);
    await page.locator('[data-settings-tab="organization"]').click();await page.locator('input[name=showProjects]').uncheck();
    await page.waitForFunction(()=>window.api.call('state').then(s=>s.settings.showProjects===false));
    assert.equal((await page.evaluate(()=>window.api.call('state'))).settings.showProjects,false);
    await page.locator('[data-view="today"]').click();
    assert.equal(await page.locator('.sidebar-collection').count(),1);
    assert.equal(await page.locator('[data-context="Office"]').count(),1);
    await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('[data-settings-tab="organization"]').click();
    await page.locator('input[name=showProjects]').check();
    await page.locator('input[name=showContexts]').uncheck();
    await page.waitForFunction(()=>window.api.call('state').then(s=>s.settings.showContexts===false));
    await page.locator('[data-view="today"]').click();
    assert.equal(await page.locator('.sidebar-collection').count(),1);
    assert.equal(await page.locator('[data-project="Work"]').count(),1);
    console.log('PASS project creation defaults, split context navigation and shortcut recording');
  }finally{if(app)await app.close();fs.rmSync(home,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
