const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {Store,parse,serialize,today}=require('../electron/store.cjs');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'machen-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('planned day survives editing and restart while creation and history retain today',t=>{
 const dir=fixture(t),store=new Store(dir);store.mutate('create',{title:'Tomorrow',scheduled:'2099-01-02'});
 const task=store.snapshot().tasks[0];assert.equal(task.created,today());assert.equal(task.scheduled,'2099-01-02');assert.equal(store.snapshot().events[0].day,today());
 store.mutate('edit',{id:task.id,title:'Still tomorrow'});assert.equal(new Store(dir).snapshot().tasks[0].scheduled,'2099-01-02');
 store.mutate('edit',{id:task.id,title:'Moved tomorrow',scheduled:'2099-01-03'});assert.equal(new Store(dir).snapshot().tasks[0].scheduled,'2099-01-03');
 assert.match(fs.readFileSync(store.file,'utf8'),/t:2099-01-03/);assert.equal(parse('Task t:2099-01-02 id:a').title,'Task');
 assert.throws(()=>store.mutate('create',{title:'Invalid',scheduled:'2026-02-31'}));
});
test('todo.txt parses dates, projects, context and completed priority',()=>{const t=parse('(A) 2026-09-08 Bericht +Arbeit @mail due:2026-09-10 id:abc');assert.equal(t.title,'Bericht +Arbeit @mail');assert.equal(t.due,'2026-09-10');assert.equal(serialize(t),'(A) 2026-09-08 Bericht +Arbeit @mail due:2026-09-10 id:abc');const c=parse('x 2026-09-09 2026-09-08 Bericht pri:A id:abc');assert.equal(c.priority,'A');assert.equal(c.completed,'2026-09-09');assert.equal(serialize(c),'x 2026-09-09 2026-09-08 Bericht pri:A id:abc');});
test('due time is stored in companion metadata without changing todo.txt',t=>{const dir=fixture(t),store=new Store(dir);store.mutate('create',{title:'Call',due:'2026-09-12',dueTime:'14:30'});const task=store.snapshot().tasks[0];assert.equal(task.dueTime,'14:30');assert.doesNotMatch(fs.readFileSync(path.join(dir,'todo.txt'),'utf8'),/14:30/);store.mutate('edit',{id:task.id,title:'Call later',due:'',dueTime:'14:30'});assert.equal(store.snapshot().tasks[0].dueTime,'');});
test('manual order persists while reordering a visible subset',t=>{const dir=fixture(t),store=new Store(dir);for(const title of ['First','Hidden','Third'])store.mutate('create',{title});const [first,hidden,third]=store.snapshot().tasks;store.mutate('reorder',{ids:[third.id,first.id]});assert.deepEqual(new Store(dir).snapshot().tasks.map(task=>task.title),['Third','Hidden','First']);assert.throws(()=>store.mutate('reorder',{ids:[hidden.id,'missing']}));});
test('subtasks and snoozed reminders persist in companion data',t=>{const dir=fixture(t),store=new Store(dir);store.mutate('create',{title:'Launch'});const id=store.snapshot().tasks[0].id;store.mutate('edit',{id,title:'Launch',subtasks:[{id:'one',title:'Review copy',done:true},{id:'two',title:'Send build',done:false}]});store.setSnooze(id,'2099-01-02T10:00:00.000Z');let task=new Store(dir).snapshot().tasks[0];assert.deepEqual(task.subtasks.map(item=>[item.title,item.done]),[['Review copy',true],['Send build',false]]);assert.equal(task.snoozedUntil,'2099-01-02T10:00:00.000Z');store.clearSnoozes([id]);assert.equal(store.snapshot().tasks[0].snoozedUntil,'');assert.throws(()=>store.mutate('edit',{id,title:'Launch',subtasks:[{id:'x',title:'',done:false}]}));});
test('create, edit, completion, reopen, deletion and context survive restart',t=>{const dir=fixture(t);let s=new Store(dir);s.mutate('create',{title:'Angebot +Büro',notes:'E-Mail\nHallo',priority:'A'});let task=s.snapshot().tasks[0];s.mutate('toggle',{id:task.id});s.mutate('toggle',{id:task.id});s=new Store(dir);assert.equal(s.snapshot().tasks[0].notes,'E-Mail\nHallo');assert.equal(s.snapshot().tasks[0].done,false);assert.equal(s.snapshot().events.length,3);s.mutate('edit',{id:task.id,title:'Angebot senden',notes:'Neu'});s.mutate('delete',{id:task.id});s=new Store(dir);assert.equal(s.snapshot().tasks.length,0);assert.equal(s.snapshot().events.at(-1).type,'delete');assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'metadata','.machen.json'))).context[task.id],undefined);assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'metadata','events.json'))).events.at(-1).type,'delete');});
test('external edits survive next write; missing ids are stable in memory',t=>{const dir=fixture(t);const s=new Store(dir);fs.writeFileSync(s.file,'2026-09-08 Extern +Arbeit\n');const id=s.snapshot().tasks[0].id;assert.equal(s.snapshot().tasks[0].id,id);s.mutate('create',{title:'Intern'});assert.equal(new Store(dir).snapshot().tasks.length,2);assert.match(fs.readFileSync(s.file,'utf8'),/Extern \+Arbeit/);});
test('invalid multiline input does not modify the file',t=>{const s=new Store(fixture(t));assert.throws(()=>s.mutate('create',{title:'one\ntwo'}));assert.equal(s.snapshot().tasks.length,0);assert.equal(fs.readFileSync(s.file,'utf8'),'');});
test('write-ahead record recovers an interrupted transaction',t=>{const dir=fixture(t);fs.writeFileSync(path.join(dir,'todo.txt'),'');fs.writeFileSync(path.join(dir,'.machen.json'),JSON.stringify({version:1,context:{},events:[],pending:`${today()} Gerettet id:abc\n`}));assert.equal(new Store(dir).snapshot().tasks[0].title,'Gerettet');assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'metadata','.machen.json'))).pending,undefined);assert.equal(fs.existsSync(path.join(dir,'.machen.json')),false);});
test('legacy metadata, attachments and backups move into the tidy storage layout',t=>{const dir=fixture(t),legacyAttachment=path.join(dir,'attachments');fs.mkdirSync(legacyAttachment);fs.writeFileSync(path.join(legacyAttachment,'mail.eml'),'Mail');fs.writeFileSync(path.join(dir,'.machen.json'),JSON.stringify({version:1,context:{abc:{notes:'Keep me',files:[{id:'file',name:'mail.eml',stored:'mail.eml'}]}},events:[{id:'event',taskId:'abc',title:'Old task',day:today(),at:new Date().toISOString(),type:'create'}]}));fs.writeFileSync(path.join(dir,'todo.txt.bak'),'Before');fs.writeFileSync(path.join(dir,'done.txt.bak'),'Before archive');const s=new Store(dir);assert.equal(s.snapshot().events[0].id,'event');assert.equal(s.meta.context.abc.notes,'Keep me');assert.equal(fs.existsSync(path.join(dir,'.machen.json')),false);assert.equal(fs.existsSync(path.join(dir,'attachments')),false);assert.equal(fs.readFileSync(path.join(dir,'metadata','attachments','mail.eml'),'utf8'),'Mail');assert.equal(fs.readFileSync(path.join(dir,'backups','todo.txt.bak'),'utf8'),'Before');assert.equal(fs.readFileSync(path.join(dir,'backups','done.txt.bak'),'utf8'),'Before archive');});
test('attachments are copied into metadata and removed with their task',t=>{const dir=fixture(t);const s=new Store(dir);s.mutate('create',{title:'Datei prüfen'});const id=s.snapshot().tasks[0].id;const source=path.join(dir,'mail.eml');fs.writeFileSync(source,'Subject: Hallo');s.attach(id,[source]);const file=s.snapshot().tasks[0].files[0],stored=s.attachment(id,file.id);fs.unlinkSync(source);assert.equal(fs.readFileSync(stored,'utf8'),'Subject: Hallo');assert.match(stored,/metadata[\\/]attachments/);assert.throws(()=>s.attachment(id,'../../secret'));s.mutate('delete',{id});assert.equal(fs.existsSync(stored),false);assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'metadata','.machen.json'))).context[id],undefined);assert.ok(fs.existsSync(path.join(dir,'backups','todo.txt.bak')));assert.ok(fs.existsSync(path.join(dir,'backups','done.txt.bak')));});
test('archive, restore and reopen preserve metadata and never duplicate tasks',t=>{
 const dir=fixture(t);let s=new Store(dir);s.mutate('create',{title:'Anrufen +Arbeit @Telefon',notes:'Details',priority:'A'});
 const id=s.snapshot().tasks[0].id;assert.throws(()=>s.mutate('archive',{id}));
 s.mutate('toggle',{id});s.mutate('archiveCompleted',{});s=new Store(dir);
 assert.equal(s.snapshot().tasks.length,0);assert.equal(s.snapshot().archived.length,1);assert.equal(s.snapshot().archived[0].notes,'Details');
 assert.match(fs.readFileSync(path.join(dir,'done.txt'),'utf8'),/^x .*@Telefon/);
 s.mutate('restore',{id});assert.equal(s.snapshot().archived.length,0);assert.equal(s.snapshot().tasks[0].done,true);
 s.mutate('archive',{id});s.mutate('toggle',{id});assert.equal(s.snapshot().tasks[0].done,false);assert.equal(s.snapshot().archived.length,0);
});
test('interrupted two-file archival recovers both todo.txt and done.txt',t=>{
 const dir=fixture(t);new Store(dir);
 const meta={version:1,context:{abc:{notes:'Keep me'}},events:[],pending:{todo:'',done:'x 2026-09-09 2026-09-08 Done @Telefon id:abc\n'}};
 fs.writeFileSync(path.join(dir,'todo.txt'),'2026-09-08 Done id:abc\n');fs.writeFileSync(path.join(dir,'.machen.json'),JSON.stringify(meta));
 const s=new Store(dir);assert.equal(s.snapshot().tasks.length,0);assert.equal(s.snapshot().archived[0].notes,'Keep me');assert.equal(s.snapshot().archived[0].id,'abc');
});
test('external archive edits are retained and history metadata remains available',t=>{
 const dir=fixture(t),s=new Store(dir);fs.writeFileSync(path.join(dir,'done.txt'),'x 2026-09-08 External id:ext\n');
 s.mutate('create',{title:'New'});assert.equal(s.snapshot().archived[0].title,'External');
 s.mutate('restore',{id:'ext'});assert.equal(s.snapshot().tasks.length,2);assert.equal(fs.readFileSync(path.join(dir,'done.txt'),'utf8'),'');
});
