// Generate the small, offline icon subset from the official Lucide SVGs.
const fs=require('node:fs');const path=require('node:path');
const names={today:'calendar-days',history:'history',all:'list-todo',settings:'settings-2',search:'search',close:'x',minimize:'minus',left:'chevron-left',right:'chevron-right',down:'chevron-down',archive:'archive',plus:'plus',check:'check',file:'paperclip',light:'sun',dark:'moon',system:'monitor'};
const icons=Object.fromEntries(Object.entries(names).map(([key,name])=>[key,fs.readFileSync(path.join(__dirname,'../node_modules/lucide-static/icons',name+'.svg'),'utf8').replace(/<svg /,'<svg aria-hidden="true" focusable="false" ')]));
fs.writeFileSync(path.join(__dirname,'../src/icons.js'),'// Generated by scripts/icons.cjs from lucide-static (ISC).\nwindow.taskIcons = '+JSON.stringify(icons,null,2)+';\n');
